### PR TITLE
All unit tests passing

### PR DESCRIPTION
**Pull request by kmracchini**
All unit tests are passing and I think I am all set with the Dao. The only issue is that I think I removed the example hibernate config file and I don't know how to get it back.  I can make you a new one, I promise!

### CODE REVIEW

**Comment by kmracchini** [comment]
Oh! I forgot to mention that I was having an issue with the assertEquals (the one that uses the overridden equals method from the entity) in the tests. I used names instead to make sure it was working, but it's not as good. So if either of you are willing to look at that and let me know if you can figure out why... that would be awesome!

**Comment by jcmann** [comment]
Could you put the sample/example hibernate config file back in? It's deleted in this, but it's helpful to have a blank one while hopping branches!

**Comment by jcmann** [comment]
deleteSuccess() and insertSuccess() are failing! 

For deleteSuccess, this is what I get: 
```
java.lang.IllegalArgumentException: attempt to create delete event with null entity

	at org.hibernate.event.spi.DeleteEvent.<init>(DeleteEvent.java:31)
	at org.hibernate.internal.SessionImpl.delete(SessionImpl.java:935)
	at com.teamcatlady.persistence.PresidentDao.delete(PresidentDao.java:179)
	at com.teamcatlady.persistence.PresidentDaoTest.deleteSuccess(PresidentDaoTest.java:96)
	....
```

This is running when we try to delete the president with the ID 3. The issue is that our IDs are not consistent, and actually are accumulating with each run of the `@BeforeEach`. So while we start with ID's 1-6 or so with the first test, the second test is working with IDs 7-12, etc. 

To fix this in my indie project, I added this line to the cleandb.sql file, immediately after the `delete from tableName` query:
```
alter table TABLENAME auto_increment = 1;
```

I believe this will also fix the insertSuccess() failure, which gives me this: 
```
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '66' for key 'presidents.number'
```

**Comment by jcmann** [comment]
Also, we might want to remove the `number` column and keep that as a stretch goal for now. President:Number is potentially a many-to-many (1 president can have many numbers, and one number can have many presidents? I think?) relationship. We could maybe add that later but I don't think it's super crucial right now.

**Comment by kmracchini** [comment]
Ok well I apparently merged this accidentally... I just wanted to add my dump from my test database to make sure it was set up the same as yours and put the hibernate example config file back.

**Pull request merged**
